[package]
name = "twentyfourtyeight"
version = "1.1.0"
authors = ["tduck973564 <tduck973564@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.2" 